const GET_USER = "USER_LOGIN";
const FETCH_GAMES = "FETCH_GAMES";
const FETCH_LANDING_PAGE_DATA = "FETCH_LANDING_PAGE_DATA";
const FILTER_DATA = "FILTER_DATA";

export { GET_USER, FETCH_GAMES, FETCH_LANDING_PAGE_DATA, FILTER_DATA };
